/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java_Advanced_12_gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
